mmtk/julia

Make.inc, contrib/refresh_checksums.mk, src/Makefile, src/array.c, src/gc-common.c, src/gc-debug.c, src/gc-pages.c, src/gc.c, src/gc.h, src/init.c, src/julia.h, src/julia_internal.h, src/julia_threads.h, src/llvm-final-gc-lowering.cpp, src/llvm-pass-helpers.cpp, src/mmtk-gc.c, src/threading.c
In preparation for upstreaming these changes.
This ended up being a pretty large set of changes, but I think most of this would have been necessary for the upstream PR anyway.
Summary of the changes:
- Build-related, to more closely match how Julia adds optional libraries. More has to be done here, for automation and for BinaryBuilder.
- Reduced the `#ifdef MMTK_GC`s.
- Documented the GC interface in `gc-interface.h`.
- Moved code that is common to Julia's GC and MMTk into `gc-common.c`.
- Exclude `gc-debug.c` and `gc-pages.c` entirely for MMTk.
- Reorganized `gc.h` into 3 parts: common, MMTk-specific, and Julia GC-specific.
- Reorganized changes to `julia.h` and `julia_internal.h`.
- Removed `#ifdef MMTK_GC` in `llvm-pass-helpers.cpp`.
We can now start working on resolving the TODOs.
=> Refactor MMTk changes to Julia

Make.inc, src/Makefile
Copies libmmtk_julia.so from the source directory (`mmtk-julia/mmtk/target/debug/libmmtk_julia.so`) to `build/usr/lib`.
=> Copy libmmtk_julia.so to usr/lib

Makefile, src/Makefile
Fixed issue that prevented building Julia or running tests with Julia's debug build. The MMTk library wasn't being copied and the tests used `julia` instead of `julia-debug` before running tests.
=> Julia's debug build and debug CI test failing

src/mmtk-gc.c, src/threading.c
Fixing assertion that compares `jl_n_gcthreads == jl_options.ngcthreads`. We set `jl_n_gcthreads = 0`, and use `jl_options.ngcthreads` to set the number of MMTk workers.
=> Set stock GC threads to 0

src/gc-common.c, src/gc.c
Need to move `jl_gc_wait_for_the_world` to `gc-common.c` as we should reuse that in both stock Julia and MMTk.
=> Refactoring the code to reuse most of jl_gc_collect in block_for_gc

src/julia_internal.h, test/threads_exec.jl
At least one of the issues with sticky immix back ported to [v1.9.2+RAI](https://github.com/mmtk/mmtk-julia/tree/v1.9.2%2BRAI) is that bindings [may occur in the remset](https://github.com/mmtk/julia/blob/c01026c91a3e2e6a064e75e0d4d4cc2f8c0d4c77/src/gc.c#L2417-L2433). However, bindings are currently skipped when scanned by MMTk since they are allocated as buffers. Therefore, we need a way to specify which bindings should actually be scanned since they were added via write barrier.
Possible sources of problems that haven't been verified yet: 
(i) can the `bits.gc` value change after being set by the write barrier? 
(ii) should we reset the value after the object has been scanned?
=> Fixing sticky immix 

src/gc.c, src/jl_exported_funcs.inc, src/julia.h, src/julia_internal.h, src/llvm-final-gc-lowering.cpp, src/llvm-late-gc-lowering.cpp, src/llvm-pass-helpers.cpp, src/llvm-pass-helpers.h, src/mmtk-gc.c
This PR makes a few changes about write barrier for bindings.
* Move the code that sets gc bits to 2 in the binding write barrier into the slowpath
* Generate code to set gc bits for binding write barrier.
* Add `unreachable()` in a few `jl_gc_wb` methods in Julia to make sure they won't be accidentally called (Julia's GC does not inline write barrier, and won't need them).
=> Fix binding write barrier for code gen

src/gc-common.c, src/gc.c, src/gc.h, src/julia_internal.h, src/mmtk-gc.c, src/threading.c
Upstream PR: https://github.com/mmtk/mmtk-core/pull/1075
=> Ask from binding if GC is disabled

src/array.c, src/gc-common.c, src/gc.c, src/julia_internal.h, src/mmtk-gc.c
When allocating an object, we are still allocating the number of bytes according to Julia's size classes, which may be an overestimation of the number of bytes an object actually requires. This PR removes this since this is specific to Julia's stock GC.
=> Stop using Julia's size classes when using MMTk

src/init.c
Calling `initialize_collection` means the language runtime is ready to do GCs. However, if I attempt to trigger a GC at the end of `initialize_collection`, the current code would fail due to two issues: 1. We cannot call `get_current_task` and `get_current_ptls`, as those are not initialized yet, and 2. some objects may get reclaimed and cause segfault if we run `julia -J sys_image.so`.
Moving the call to `initialize_collection` as the last step in `julia_init` fixes the issues.
=> Call initialize_collection after _finish_julia_init

Make.inc, base/options.jl, src/gc.c, src/jloptions.c, src/jloptions.h
This PR introduces fixed heap size for stock Julia. With the build time option `WITH_GC_FIXED_HEAP=1` and using `--fixed-heap-size=...`, it will bypass all the existing GC triggering heuristics, and only do GC when the heap size reaches the defined heap size, and will only do a full heap GC if the free memory after a GC is less than 20% of the heap size.
This PR also introduces a global counter for mallocd bytes. This will slow down the performance of malloc. For MMTK Julia, we also use such a counter (see https://github.com/mmtk/mmtk-julia/issues/141). I plan to do another PR to fix this for both MMTK Julia and stock Julia.
=> Implement fixed heap size for Julia

src/gc.h, src/julia_threads.h, src/threading.c
These functions do not include GC safe points. But without marking them as `JL_NOTSAFEPOINT`, the GC checker will report errors in other places.
=> Fix a few places where GC static analyzer will report as errors

src/init.c
This PR fixes https://github.com/mmtk/mmtk-core/issues/1096. We should call `initialize_collection` before enabling GC. Related discussion here: https://github.com/mmtk/julia/pull/39#discussion_r1503650745
=> Call initialize_collection before enabling GC

src/interpreter.c, src/julia.h
Supporting pushing roots to the shadow stack that are not transitively pinned (only the root object is pinned), and therefore should enable moving more objects.
For backwards compatibility the original functions will be used to represent transitively pinned roots, whereas the `*_RELAXED` version will represent roots in which only the root object needs to be pinned. Therefore, to support moving move objects the goal is to replace as much as possible of the original functions with their `_RELAXED` counterpart.
=> Adding macros to push pinning roots

src/mmtk-gc.c
I'm actually not 100% sure about this change, but I think it kind of makes sense if we want heap resizing as default, since membalancer doesn't really work. Happy to discuss further.
=> Using Julia's stock GC trigger/heuristics as default

src/gc-common.c, src/gc.c, src/julia_gcext.h, src/julia_threads.h, src/options.h, src/signals-unix.c
Cherry-picking changes from https://github.com/JuliaLang/julia/pull/55003 to enable saving registers of tasks that were active right before GC.
NB: Some changes need to be propagated to https://github.com/mmtk/mmtk-julia to reflect the changes in `jl_tls_states_t`: see https://github.com/mmtk/mmtk-julia/pull/159.
=> WIP: save registers of tasks that were active right before GC on a ucontext_t for conservative scanning

src/ast.c, src/cgutils.cpp, src/jitlayers.h
Julia may embed heap pointers in the code. Those objects cannot be moved, otherwise the pointer value in the code becomes invalid. This PR pins those pointers in `literal_pointer_val` and `literal_static_pointer_val`.
Julia also reference heap pointers from scm/flisp values. We pin those heap pointers in `julia_to_scm_`.
=> Pin pointer literals in code, and julia values in julia_to_scm

base/options.jl, src/jloptions.c, src/jloptions.h, src/llvm-late-gc-lowering.cpp
Adding runtime option to inline fastpath allocation for MMTk.
=> Adding runtime option to inline allocation fastpath

src/gc-interface.h, src/gc-mmtk.c, src/gc-stock.c, stdlib/REPL/src/REPL.jl
Just added a piece of text when starting Julia so we know it's been built with MMTk.
=> Adding `GC: MMTk` tag to Julia's banner when building with MMTk

.github/workflows/StockBuild.yml, src/Makefile, src/gc-debug.c, src/gc-interface.h, src/gc-mmtk.c, src/gc-mmtk.h, src/gc-page-profiler.c, src/gc-pages.c, src/gc-stacks.c, src/gc-stock.c, src/gc-stock.h, src/gc-tls-mmtk.h, src/gc-tls-stock.h, src/genericmemory.c, src/julia_threads.h
This PR changes the build script to only include source files for the GC implementation that is selected. The PR also removes unnecessary preprocessor `#ifdef` for related files.
This PR adds a CI job to build with the stock GC. This helps us to make sure that the stock GC can build.
=> Conditionally compile GC source files. Test stock build in CI.

src/datatype.c, src/gc-interface.h, src/gc-mmtk.c, src/gc-stock.c, src/julia.h, src/llvm-late-gc-lowering-mmtk.cpp, src/symbol.c
This PR ports https://github.com/mmtk/julia/pull/59 to `dev`. In addition, this PR 1. introduces `jl_gc_permsymbol` for allocating the special perm object in `mk_symbol`, 2. removes some seemingly unnecessary post alloc calls for `jl_gc_perm_alloc` in `datatype.c`, and 3. does not support set VO bit using the slowpath (MMTk call).
=> Support VO bit

src/gc-interface.h, src/gc-mmtk.c, src/gc-stock.c, src/gc-tls-mmtk.h, src/signals-unix.c
This PR ports https://github.com/mmtk/mmtk-julia/pull/159 to `dev`. The difference is that this PR adds a general call to the GC interface `jl_gc_notify_thread_yield`. In this case, each GC will do what they need in the call, and the context is saved in the GC specific TLS.
=> Save thread context before yielding for GC

Make.inc, src/Makefile
Removing `WITH_MMTK` and deciding whether to build with MMTk based on `MMTK_PLAN`.
=> Removing `WITH_MMTK`

Make.inc, src/Makefile
This is complementary to https://github.com/mmtk/julia/pull/79 but adding `None` as default value for `MMTK_PLAN` and handling it in the Makefile.
=> Adding None as a default value for `MMTK_PLAN`

src/ast.c, src/engine.cpp, src/gc-common.c, src/gc-mmtk.c, src/julia.h
Following the suggestion in https://github.com/mmtk/julia/pull/89#issuecomment-2982261402, trace recently added pinned objects as roots. When we pass those objects as 'nodes' to MMTk, MMTk does not know the slots so MMTk cannot update the reference, thus MMTk will not move those objects. This is essentially the same as pinning those objects before a GC, and unpinning after a GC.
=> Trace pinned objects as roots
